w01/diary/urls.py
from django.urls import path,include
from . import views

app_name = "diary"
urlpatterns = [
    path('diaryHome/', views.diaryHome, name="diaryHome"),
    path('MdiaryList/', views.MdiaryList, name="MdiaryList"),
    path('diaryWrite/', views.diaryWrite, name="diaryWrite"),
    path('diaryMake/', views.diaryMake, name="diaryMake"),
    path('diaryView/', views.diaryView, name="diaryView"),
]

w01/w01/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin1/', include('admin1.urls')),
    path('loginpage/', include('loginpage.urls')),
    path('customer/', include('customer.urls')),
    path('emotion/', include('emotion.urls')),
    path('', include('home.urls')),
    path('diary/', include('diary.urls')),
    path('mypage/', include('mypage.urls')),
    path('comment/', include('comment.urls')),
    path('calendar1/', include('calendar1.urls')),
    path('family1/', include('family1.urls')),
]


# settings.py 안에
# MEDIA_URL = 'media/' 로 들어오면
# MEDIA_ROOT = os.path.join(BASE_DIR,'media') 에서 찾아라
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

w01/diary/models.py
from django.db import models
from loginpage.models import Member
from django.core.exceptions import ValidationError

    
# 개인 다이어리 테이블
class MdiaryBoard(models.Model):
  mno = models.AutoField(primary_key=True)
  id = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=True)
  mtitle = models.CharField(max_length=1000)
  mdate = models.DateField(null=True)

  def __str__(self):
    return f"{self.mno},{self.id.id},{self.id.nicName},{self.mtitle},{self.mdate}"
  

  
  
# 우체통
from loginpage.models import Member
class Letter(models.Model):
  lno = models.AutoField(primary_key=True)
  member = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=True)
  ltitle = models.CharField(max_length=1000)
  lcontent = models.TextField()
  ldate = models.DateTimeField(auto_now=True)
  lhit = models.IntegerField(default=0)

  def __str__(self):
    return f"{self.lno},{self.member},{self.ltitle},{self.lcontent},{self.ldate}"
  
  
# 그룹 다이어리 db 나중에 그룹 다이어리 생성 시 중복 체크해서 raise ValidationError("이미 그룹 다이어리가 존재합니다.")
# 한 아이디가 하나의 그룹 다이어리 생성 할 수 있도록
class GroupDiary(models.Model):
  gno = models.AutoField(primary_key=True)
  member = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=False)
  gtitle = models.CharField(max_length=200)
  gName = models.CharField(max_length=100, null=False, default="우리가족") # 그룹이름
  created_at = models.DateTimeField(auto_now_add=True)
  
  def __str__(self):
    return f"{self.gno},{self.member.id},{self.gtitle},{self.gName},{self.created_at}"

  def clean(self):
    # 같은 사용자가 이미 그룹 다이어리를 생성한 경우 ValidationError 발생
    if GroupDiary.objects.filter(member=self.member).exists():
        raise ValidationError("이미 그룹 다이어리가 존재합니다.")


# 다이어리 작성 -> 내용 db
from django.utils import timezone
class Content(models.Model):
  cno = models.AutoField(primary_key=True)
  member = models.ForeignKey(Member,on_delete=models.DO_NOTHING, null=False) # 유저id & 닉네임 가져옴
  ctitle = models.CharField(max_length=1000)
  ccontent = models.TextField(null=True)
  cdate = models.DateField(default=timezone.now)  # 기본값을 오늘 날짜로 설정
  group_diary  = models.ForeignKey(GroupDiary, on_delete=models.CASCADE, null=True, blank=True)
  # 공용다이어리 db 만들면 추후 업데이트
  image = models.ImageField(upload_to='diary_images/', blank=True, null=True)  # 이미지

  def __str__(self):
    return f"{self.cno},{self.member.id},{self.ctitle},{self.ccontent},{self.cdate},{self.group_diary},{self.member.nicName}"

w01/diary/views.py
from django.shortcuts import render, redirect
from django.shortcuts import render,redirect
from loginpage.models import Member
from diary.models import Letter
from loginpage.models import Member
from django.utils import timezone
from diary.models import Content
from diary.models import GroupDiary
from django.http import HttpResponse


# 우체통
from .models import MdiaryBoard

## 다이어리 HOME
def diaryHome(request):
  id = request.session.get('session_id')
  ## 공유 일기장
  # 유저가 생성한 공유일기장
  qs_createdDiary = GroupDiary.objects.filter(member__id=id)
  qs_cmember = Member.objects.filter(joined_group=qs_createdDiary[0].gno) # 가입멤버

  if qs_createdDiary:
    c_context = {"createdDiary":qs_createdDiary[0],"cmembers":qs_cmember}
    return render(request,'diaryHome.html',c_context)
  
  # # 유저가 가입한 공유일기장
  qs_joinedDiary = GroupDiary.objects.filter(gno=Member.joined_group)
  qs_jmember = Member.objects.get(created_group=qs_createdDiary[0].gno) # 방장
  qs_jmembers = Member.objects.filter(joined_group=qs_createdDiary[0].gno) # 가입멤버
  if qs_joinedDiary:
    j_context = {"joinedDiary":qs_joinedDiary,"jmem":qs_jmember,"jmembers":qs_jmembers}
    return render(request,'diaryHome.html',j_context)


  # if qs_createdDiary:
  #   if qs_joinedDiary:
  #     d_context = {"createdDiary":qs_createdDiary,"joined_diary":qs_joinedDiary}
  #     return render(request,'diaryHome.html',d_context)
  #   else:
  #     d_context = {"createdDiary":qs_createdDiary}
  #     return render(request,'diaryHome.html',d_context)
  # # 유저가 가입한 공유일기장
  # if qs_joinedDiary:
  #   if not qs_createdDiary:
  #     d_context = {"joined_diary":qs_joinedDiary}
  #     return render(request,'diaryHome.html',d_context)


  # 우체통
  qs = Letter.objects.all().order_by("ldate")
  member = Member.objects.filter(id=id)
  # personal_diaries = MdiaryBoard.objects.select_related('id').all() # 개인 다이어리 데이터 가져오기
  if member:
    user_nic = member[0].nicName
    context = {"list":qs ,'user_nic':user_nic}
    return render(request,'diaryHome.html',context)
  else:
    context = {'list':qs}
    return render(request,'diaryHome.html',context)
  
    



## 가족다이어리 생성
def diaryMake(request):
  if request.method == 'GET':
    qs = Member.objects.all()
    context = {'members':qs}
    return render(request,'diaryMake.html', context)
  else:
    id = request.session['session_id']
    member = Member.objects.get(id=id)
    gtitle = request.POST.get('gtitle')
    gName = request.POST.get('gName')
    created_at = request.POST.get('created_at','')
    search_members = request.POST.getlist('search_members[]')

    qs_gDiary = GroupDiary.objects.create(gtitle=gtitle, gName=gName, created_at=created_at, member=member)

    
    qs_cMem = Member.objects.get(id=id)
    qs_cMem.created_group = qs_gDiary
    qs_cMem.save()

    for member in search_members:
      qs = Member.objects.get(id=member)
      qs.joined_group = qs_gDiary
      qs.save()
    
    context = {"gmsg":"1"}
    return render(request, 'diaryHome.html', context)
    




## 내 다이어리 목록
# def MdiaryList(request):
#   qs = Content.objects.all().order_by("-cdate")
#   context = {'content':qs}  
#   return render(request,'MdiaryList.html', context)

from django.contrib.auth.decorators import login_required

@login_required
def MdiaryList(request):
    if request.method == "GET":
        # 세션에 저장된 ID 가져오기
        session_id = request.session.get('session_id')  # 세션에서 'session_id'를 가져옴
        print("세션아이디:", session_id)

        # 세션에 해당하는 ID가 존재하는지 확인
        if not session_id:
            return render(request, 'error.html', {'message': '세션 ID가 존재하지 않습니다.'})
        
        # session_id를 기준으로 Member 찾기
        member = Member.objects.filter(id=session_id).first()

        # member가 없으면 에러 처리
        if not member:
            return render(request, 'error.html', {'message': '사용자 정보가 존재하지 않습니다.'})

        # 해당 멤버의 Content 가져오기
        qs = Content.objects.filter(member=member).order_by("-cdate")
        context = {'content': qs}
        return render(request, 'MdiaryList.html', context)






# 다이어리 작성 저장
def diaryWrite(request):
    if request.method == "GET":
        # 세션에서 사용자 ID 가져오기
        id = request.session.get('session_id')  # 현재 사용자의 ID 가져오기
        current_date = timezone.now().date().strftime('%Y-%m-%d')

        # 생성한 그룹과 참여한 그룹 가져오기
        created_group = GroupDiary.objects.filter(member__id=id).first()
        joined_group = GroupDiary.objects.filter(members__id=id).first()

        return render(request, 'diaryWrite.html', {
            'current_date': current_date,
            'created_group': created_group,
            'joined_group': joined_group,
        })
    
    elif request.method == "POST":
        # 세션에서 사용자 ID 가져오기
        id = request.session.get('session_id')  # 세션에서 사용자 ID 가져오기
        
        if not id:
            return HttpResponse("로그인 정보가 없습니다.", status=400)

        # Member 모델에서 해당 ID로 회원 조회
        member = Member.objects.filter(id=id).first()  # 없으면 None 반환
        
        if not member:
            return HttpResponse("사용자 정보가 존재하지 않습니다.", status=400)
        
        # 다이어리 작성 내용 저장
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        
        # 로그인 후 첫 접속 시 세션에 diary_count 초기화 (새로운 세션 시작)
        if f"diary_count_{id}" not in request.session:
            request.session[f"diary_count_{id}"] = 1
        else:
            # 세션에 diary_count가 있으면 증가
            diary_count = request.session[f"diary_count_{id}"] + 1
            request.session[f"diary_count_{id}"] = diary_count

        # cno는 세션 고유 번호로 관리된 카운터 값 사용
        cno = str(request.session[f"diary_count_{id}"])

        # Content 객체 생성하여 저장
        new_diary = Content(
            cno=cno, #생성된 cno사용
            member=member, 
            ctitle=title,
            ccontent=content,
            image=image,
            cdate=timezone.now().date()
        )
        new_diary.save()

        return redirect('diary:MdiaryList')  # 다이어리 리스트로 리다이렉트


# 다이어리 view 추후 업데이트 >>
def diaryView(request):
    id = request.session.get('session_id')
    member = Member.objects.filter(id=id)
    qs = Content.objects.filter(member=member[0])
    context = {"content":qs}
    return render(request,'diary_view.html',context)

w01/diary/templates/diaryMake.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static '/css/diary/diary_make.css'%}">
  <link rel="stylesheet" href="{% static '/css/home/main.css'%}">
  <script  src="http://code.jquery.com/jquery-latest.min.js"></script>
  <title>가족 공유 다이어리 생성</title>
  
<!-- 공통 상단좌측메뉴 -->
<script>
  $(function() {
    // GNB 클릭
    $('#menu ul li').on('click', function() {
      $('#menu ul li').removeClass('active');
      $(this).addClass('active');
    });
  });
</script>
</head>
<body>
<!-- 최상단 메뉴 -->
<div id="top_nav">
  <h1><a href="#"></a></h1>
  <ul class="top_menu">
    <li><a href="#"><img src="/static/images/home/search_icon.png" alt=""></a></li>
    <li><a href="#"><img src="/static/images/home/bell_off_icon.png" alt=""></a></li>
    <li><a href="#">마이페이지</a></li>
  </ul>

</div>

<!-- 좌측 gnb -->
<div id="gnb">

  <!-- 프로필 -->
  <div id="user_profile">
    <div id="pimg">
      <img src="/static/images/home/default_profile.png" alt="">
    </div>
    <p id="uName">김용준</p>
    <p id="uEmail">kyjoon0105@gmail.com</p>
  </div>

  <!-- Nav -->
  <nav id="menu">
    <ul>
      <a href="#"><li class="menu_item">우리 가족 이야기</li></a>
      <a href="#"><li class="menu_item active">다이어리</li></a>
      <a href="#"><li class="menu_item">감정 돌아보기</li></a>
      <a href="#"><li class="menu_item">우리가족</li></a>
      <a href="#"><li class="menu_item">캘린더</li></a>
      <a href="#"><li class="menu_item">알려드려요</li></a>
    </ul>
  </nav>

  <!-- logout -->
  <div id="logout">
    <a href="#"><span>로그아웃</span></a>
  </div>
  
</div>
<!-- 공통 상단좌측메뉴 -->


<!-- 다이어리 HOME -->
<div id="all_area">
  <!-- 상단부분 -->
  <div id="title_area">
    <p id="topTit">가족 공유 다이어리 만들기</p>      
  </div>

  <!-- 메인부분 -->
  <div id="main_area">
    <div class="container">
      <img id="diaryImg" src="/static/images/diary/diaryMake.png" alt="Family Diary Background">
      <form action="" method="post" id="diaryFrm" name="diaryFrm">
        {% csrf_token %}
        <div class="title_container">
          <div>
            <span>다이어리 제목</span>
          </div>
          <div>
            <input type="text" id="title" name='gtitle' class="title_input" placeholder="제목을 입력하세요." maxlength="20"></input>
          </div>
          
          <div id="groupName">
            <span>가족 이름</span><br>
            <div class="gName_container">
              <input type="text" id='gName' name="gName" class="familyName" placeholder="우리 가족의 이름을 정해보세요." maxlength="20">
            </div>
          </div>
          
          <div id="mem_search">
            <span>추가할 가족 검색</span><br>
            <div id="search_container">
              <input id="searchBar" class="searchBar" type="text" name="search" placeholder="검색">
              <button type="button">검색</button>
              <ul id="mList" style="display:none;">
                {% for member in members %}
                  <li>{{ member.id }}</li>
                  <li>{{ member.name }}</li>
                {% endfor %}
              </ul>
            </div>
            <div id="memberList">
              
            </div>
          </div>
        
          <div id="date_search">
            <span>다이어리 생성일</span><br>
            <input type="date" id='gdate' name='created_at' class="date_input">
          </div>
        
          <div id="save_area">
            <button id="saveBtn" type='button'><img src="/static/images/diary/saveBtn.png" alt=""></button>
            <span id="cancelBtn"><button><img src="/static/images/diary/cancleBtn.png" alt=""></button></span>
          </div>
        </div>
      </form>
    </div>
  </div>
    
  <!-- 스크립트 부분 -->
  <script>
    $(document).ready(function () {
      const members = []; // ID와 Name을 저장할 배열
    
      // #mList의 <li>들을 순회하며 처리
      $('#mList li:nth-child(odd)').each(function (index) {
        const memberId = $(this).text().trim(); // 홀수 번째 <li>는 ID
        const memberName = $('#mList li:nth-child(even)').eq(index).text().trim(); // 짝수 번째 <li>는 Name
    
        members.push({ id: memberId, name: memberName }); // 객체로 저장
      });
      
      // 엔터키 입력 방지 및 버튼 클릭 트리거
      $('#searchBar').on('keypress', function (event) {
        if (event.key === 'Enter') {
          event.preventDefault(); // 기본 제출 방지
          $('#search_container button').click(); // 버튼 클릭 트리거
        }
      });
      // 검색 버튼 클릭 이벤트 처리
      $('#search_container button').on('click', function () {
        const input_id = $('#searchBar').val().trim(); // 입력값 가져오기
    
        // 입력값과 일치하는 회원 찾기
        const member = members.find(m => m.id === input_id);
    
        if (member) {
          // 일치하는 회원이 있을 경우 이름 추가
          $('#memberList').append(`<div class='nicName'>${member.name}</div>`); // 이름 텍스트 추가
          $('#diaryFrm').append(`<input type="hidden" name="search_members[]" value="${member.id}">`); // 검색해서 추가한 멤버id hidden 저장
          alert(`"${input_id}" 회원을 찾았어요!`);
          $("#searchBar").val('')
        } else {
          // 일치하는 회원이 없을 경우 메시지 출력
          alert(`"${input_id}"는 회원 정보와 일치하지 않아요.`);
          $("#searchBar").val('')
        }
      });

      $("#saveBtn").click(function(){
        if($("#title").val().length<1){
          alert("다이어리 제목을 입력하세요.");
          return false;
        }
        if($("#gName").val().length<1){
          alert("가족 이름을 입력하세요.");
          return false;
        }
        if ($("#memberList").children().length < 1) {
          alert("가족을 추가하세요.");
          return false;
        }
        diaryFrm.submit()
      });
    });
  </script>


  
</body>
</html>

w01/diary/templates/diaryWrite.html
{%load static%}
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/diary/diary_write.css'%}">
  <link rel="stylesheet" href="{% static 'css/home/main.css'%}">
  <link rel="stylesheet" as="style" crossorigin
    href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css" />
  <script src="http://code.jquery.com/jquery-latest.min.js"></script>
  <title>다이어리 작성</title>
</head>

<!-- 공통 상단좌측메뉴 -->
<script>
  $(function () {
    // GNB 클릭
    $('#menu ul li').on('click', function () {
      $('#menu ul li').removeClass('active');
      $(this).addClass('active');
    });
  });

  
</script>
</head>

<body>
  <!-- 최상단 메뉴 -->
  <div id="top_nav">
    <h1><a href="#"></a></h1>
    <ul class="top_menu">
      <li><a href="#"><img src="/static/images/home/search_icon.png" alt=""></a></li>
      <li><a href="#"><img src="/static/images/home/bell_off_icon.png" alt=""></a></li>
      <li><a href="#">마이페이지</a></li>
    </ul>

  </div>

  <!-- 좌측 gnb -->
  <div id="gnb">

    <!-- 프로필 -->
    <div id="user_profile">
      <div id="pimg">
        <img src="/static/images/home/default_profile.png" alt="">
      </div>
      <p id="uName">김용준</p>
      <p id="uEmail">kyjoon0105@gmail.com</p>
    </div>

    <!-- Nav -->
    <nav id="menu">
      <ul>
        <a href="#">
          <li class="menu_item">우리 가족 이야기</li>
        </a>
        <a href="#">
          <li class="menu_item active">다이어리</li>
        </a>
        <a href="#">
          <li class="menu_item">감정 돌아보기</li>
        </a>
        <a href="#">
          <li class="menu_item">우리가족</li>
        </a>
        <a href="#">
          <li class="menu_item">캘린더</li>
        </a>
        <a href="#">
          <li class="menu_item">알려드려요</li>
        </a>
      </ul>
    </nav>

    <!-- logout -->
    <div id="logout">
      <a href="#"><span>로그아웃</span></a>
    </div>

  </div>
  <!-- 공통 상단좌측메뉴 -->

  <!-- 다이어리 작성 메인 -->
  <div id="diary_write">
    <h1>일기 작성</h1>
    <form action= "{% url 'diary:diaryWrite' %}" id="writeFrm" name="writeFrm" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        <label for="title">제목</label>
        <input type="text" name="title" id="title" placeholder="제목을 입력해주세요." required>
      </div>
      <div class="form-group">
        <!-- 생성 날짜 자동 기입(db) -->
        <label for="date">오늘 날짜</label>
        <input type="date" name="date" id="date" value="{{ current_date }}">
      </div>
      <!-- 사진 업로드 -->
      <div class="form-group">
        <label for="image">사진 업로드</label>
        <div class="file-input-container">
          <input type="file" id="image" name="image" multiple accept="image/*" onchange="previewImages(event)">
        </div>

        <!-- 이미지 미리보기 영역 -->
        <div class="image-preview-container" id="image-preview-container"></div>
      </div>
      <div class="form-group">
        <label for="content">내용</label>
        <textarea name="content" id="content" rows="10" oninput="autoResize(this)" placeholder="내용을 입력해주세요."
          required></textarea>
      </div>

      <!-- 다이어리 체크박스 예시 -->
      <!-- {% if diaries %}
      <div>
        <p>공유 다이어리에 등록합니다:</p>
        {% for diary in diaries %}
        <label>
          <input type="checkbox" name="diary_ids" value="{{ diary.id }}">
          {{ diary.title }}
        </label><br>
        {% endfor %}
      </div>
      {% else %}
      <p>공유 가능한 다이어리가 없습니다.</p>
      {% endif %} -->

      {% if created_group or joined_group %}
      <div class="form-group">
          <label>공유</label><br>

          {% if created_group %}
          <label id="fdiary">
              {{ created_group.gName }}
              <input type="checkbox" id="share" name="diary_ids" value="{{ created_group.gno }}">
          </label>
          {% endif %}

          {% if joined_group %}
          <label id="fdiary">
              {{ joined_group.gName }}
              <input type="checkbox" id="share" name="diary_ids" value="{{ joined_group.gno }}">
          </label>
          {% endif %}
      </div>
      {% endif %}

      <button type="submit" onclick='saveBtn(event)' class="save">저장</button>
      <button type="button" class="cancel" onclick="confirmCancel()">취소</button>
  </div>
  </form>

  <!-- 확대된 이미지 팝업 -->
  <div class="image-popup" id="image-popup">
    <span class="close-popup" onclick="closePopup()">×</span>
    <img id="popup-image" src="" alt="Enlarged Image">
  </div>

  
</div>
<script type="text/javascript">

  {% comment %} var checkUnload = true;
    $(window).on('beforeunload', function () {
        if (checkUnload) return "이 페이지를 벗어나면 작성된 내용은 저장되지 않습니다.";
    });
    $("#write").on("click", function () {
        checkUnload = false;
        $("submit").submit();
    }); {% endcomment %}

  // 다이어리 저장 후 알림 처리 및 페이지 이동
  function saveBtn(event) {
    event.preventDefault();  // 폼이 자동으로 제출되는 것을 방지
    if ($("#title").val().length < 1) {
      alert("제목을 입력해주세요.");
      $("#title").focus();
      return false;
    }
    writeFrm.submit()
  }
    
  // 취소 버튼 클릭 시 확인 메시지
  function confirmCancel() {
    var confirmAction = confirm("정말 취소하시겠습니까?");
    if (confirmAction) {
      window.location.href = '/diary/MdiaryList/';  // 취소 후 이동
    }
  }

  if ("{{wmsg}}" == "1"){
    alert("저장되었습니다.")
    location.href = '/diary/MdiaryList/'
  }
  
  function autoResize(textarea) {
    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
  }

  // 이미지 미리보기 및 여러 이미지 처리
  function previewImages(event) {
    const files = event.target.files;  // 업로드된 파일 목록
    const previewContainer = document.getElementById('image-preview-container');

    // 기존 이미지가 있다면 유지하고 새로운 이미지를 추가
    Array.from(files).forEach(file => {
      const reader = new FileReader();

      reader.onload = function (e) {
        const img = document.createElement('img');
        img.src = e.target.result;  // 이미지 데이터를 URL로 설정
        img.onclick = function () {
          openPopup(img.src);  // 이미지 클릭 시 확대 보기
        };
        previewContainer.appendChild(img);  // 이미지 미리보기 영역에 추가
      };

      reader.onerror = function (error) {
        console.error("파일 읽기 오류:", error);
      };

      reader.readAsDataURL(file);  // 파일을 데이터 URL로 읽어 이미지 미리보기
    });
  }

  // 이미지 확대 보기 팝업 열기
  function openPopup(imageSrc) {
    const popup = document.getElementById('image-popup');
    const popupImage = document.getElementById('popup-image');
    popup.style.display = 'flex';
    popupImage.src = imageSrc;
  }

  // 이미지 확대 보기 팝업 닫기
  function closePopup() {
    const popup = document.getElementById('image-popup');
    popup.style.display = 'none';
  }

  //이미지 삭제
  function previewImages(event) {
    const files = event.target.files; // 업로드된 파일 목록
    const previewContainer = document.getElementById('image-preview-container');
  
    Array.from(files).forEach(file => {
      const reader = new FileReader();
  
      reader.onload = function (e) {
        // 이미지와 삭제 버튼을 감싸는 wrapper 생성
        const wrapper = document.createElement('div');
        wrapper.classList.add('image-wrapper');
        wrapper.style.position = 'relative';
        wrapper.style.display = 'inline-block';
  
        // 이미지 생성
        const img = document.createElement('img');
        img.src = e.target.result; // 이미지 데이터를 URL로 설정
        img.alt = 'Uploaded image';
        img.onclick = function () {
          openPopup(img.src); // 이미지 클릭 시 확대 보기
        };
  
        // 삭제 버튼 생성
        const deleteButton = document.createElement('button');
        deleteButton.classList.add('delete-button');
        deleteButton.innerText = '×';
        deleteButton.onclick = function () {
          wrapper.remove(); // 이미지 wrapper 삭제
        };
  
        // wrapper에 이미지와 버튼 추가
        wrapper.appendChild(img);
        wrapper.appendChild(deleteButton);
  
        // 미리보기 컨테이너에 wrapper 추가
        previewContainer.appendChild(wrapper);
      };
  
      reader.onerror = function (error) {
        console.error("파일 읽기 오류:", error);
      };
  
      reader.readAsDataURL(file); // 파일을 데이터 URL로 읽어 이미지 미리보기
    });
  }
  
  // 이미지 확대 보기 팝업 열기
  function openPopup(imageSrc) {
    const popup = document.getElementById('image-popup');
    const popupImage = document.getElementById('popup-image');
    popup.style.display = 'flex';
    popupImage.src = imageSrc;
  }
  
  // 이미지 확대 보기 팝업 닫기
  function closePopup() {
    const popup = document.getElementById('image-popup');
    popup.style.display = 'none';
  }
  

</script>


</body>

</html>